# Generated by Django 3.0.9 on 2020-10-17 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=30)),
                ('question_2', models.CharField(max_length=30)),
                ('question_3', models.CharField(max_length=30)),
                ('question_4', models.CharField(max_length=30)),
                ('question_5', models.CharField(max_length=30)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=25)),
                ('phone', models.IntegerField(blank=True)),
                ('father_name', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=20)),
                ('guidancephone', models.CharField(blank=True, max_length=15)),
                ('cgpa', models.CharField(blank=True, max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Makequestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(blank=True, max_length=500)),
                ('mcq_1', models.CharField(blank=True, max_length=500)),
                ('mcq_2', models.CharField(blank=True, max_length=500)),
                ('mcq_3', models.CharField(blank=True, max_length=500)),
                ('mcq_4', models.CharField(blank=True, max_length=500)),
                ('mcq_5', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ans_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sapp.Questions')),
            ],
            options={
                'verbose_name': 'Make Questions',
                'verbose_name_plural': 'Make Questions',
            },
        ),
    ]
