# Generated by Django 3.0.9 on 2020-10-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makequestion',
            name='ans_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sapp.Questions'),
        ),
    ]
