# Generated by Django 3.0.9 on 2020-10-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20201017_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsFieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=30)),
                ('question_2', models.CharField(max_length=30)),
                ('question_3', models.CharField(max_length=30)),
                ('question_4', models.CharField(max_length=30)),
                ('question_5', models.CharField(max_length=30)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Answers',
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Answers', 'verbose_name_plural': 'Answers'},
        ),
    ]
