# Generated by Django 3.0.9 on 2020-10-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_auto_20201020_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsfieldname',
            options={'verbose_name': 'Questions Field Name', 'verbose_name_plural': 'Questions Field Name'},
        ),
        migrations.RemoveField(
            model_name='questionsfieldname',
            name='user_id',
        ),
    ]
