# Generated by Django 3.0.9 on 2020-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0004_auto_20201020_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionsFieldName',
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
