# Generated by Django 3.0.9 on 2020-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0005_auto_20201020_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
