# Generated by Django 3.0.9 on 2020-10-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0006_auto_20201020_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
