# Generated by Django 3.0.9 on 2020-10-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0007_auto_20201020_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makequestion',
            name='ans_num',
        ),
    ]
